/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ImageType = IDL.Variant({
  'png' : IDL.Null,
  'jpeg' : IDL.Null,
  'webp' : IDL.Null,
});
export const ImageMetadata = IDL.Record({
  'imageType' : ImageType,
  'description' : IDL.Text,
  'uploadTimestamp' : IDL.Int,
  'filename' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllImageMetadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ImageMetadata))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHomepageImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getImageMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ImageMetadata)],
      ['query'],
    ),
  'getLogoImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadHomepageImage' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Int, ImageType],
      [],
      [],
    ),
  'uploadImage' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Int, ImageType, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadLogo' : IDL.Func([ExternalBlob, IDL.Text, IDL.Int, ImageType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ImageType = IDL.Variant({
    'png' : IDL.Null,
    'jpeg' : IDL.Null,
    'webp' : IDL.Null,
  });
  const ImageMetadata = IDL.Record({
    'imageType' : ImageType,
    'description' : IDL.Text,
    'uploadTimestamp' : IDL.Int,
    'filename' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllImageMetadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ImageMetadata))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHomepageImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getImageMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImageMetadata)],
        ['query'],
      ),
    'getLogoImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadHomepageImage' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Int, ImageType],
        [],
        [],
      ),
    'uploadImage' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Int, ImageType, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadLogo' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Int, ImageType],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };